import { Color } from "./themeModal";
export const THEMES = {
	light: {
		"--whiteToLightBlue": Color.WHITE,
		"--whiteToInherit": Color.WHITE,
		"--darkBlueTextToLightBlueText": Color.DARK_BLUE_TEXT,
		"--lightGreyToLightBlue": Color.LIGHT_GREY,
		"--lightGreyToDarkestBlue": Color.LIGHT_GREY,
		"--mediumGreyToMediumBlue": Color.MEDIUM_GREY,
		"--mediumGreyToLightBlue": Color.MEDIUM_GREY,
		"--darkGreyToDarkestBlue": Color.DARK_GREY,
		"--darkGreyToDarkBlue": Color.DARK_GREY,
		"--blackTextToBlueText": Color.BLACK_TEXT,
		"--blackTextToWhiteText": Color.BLACK_TEXT,
		"--greyTextToWhiteText": Color.GREY_TEXT,
		"--greyBorderToBlueBorder": Color.GREY_BORDER,
		"--whiteToSideBarBlue": Color.WHITE,
		"--blackSvgToWhiteSvg": Color.SVG_BLACK,
		"--darkestBlueToInherit": Color.DARKEST_BLUE,
	},

	dark: {
		"--whiteToLightBlue": Color.LIGHT_BLUE,
		"--whiteToInherit": Color.INHERIT_COLOR,
		"--darkBlueTextToLightBlueText": Color.BLUE_BORDER,
		"--lightGreyToLightBlue": Color.LIGHT_BLUE,
		"--lightGreyToDarkestBlue": Color.DARKEST_BLUE,
		"--mediumGreyToMediumBlue": Color.MEDIUM_BLUE,
		"--mediumGreyToLightBlue": Color.LIGHT_BLUE,
		"--darkGreyToDarkestBlue": Color.DARKEST_BLUE,
		"--darkGreyToDarkBlue": Color.DARK_BLUE,
		"--blackTextToBlueText": Color.BLUE_TEXT,
		"--blackTextToWhiteText": Color.WHITE,
		"--greyTextToWhiteText": Color.WHITE,
		"--greyBorderToBlueBorder": Color.BLUE_BORDER,
		"--whiteToSideBarBlue": Color.RIGHT_SIDE_BAR_BLUE,
		"--blackSvgToWhiteSvg": Color.SVG_WHITE,
		"--darkestBlueToInherit": Color.INHERIT_COLOR,
	},
};
